-- Task 13
--
-- Instructions
--
--     Construire une analyse croisée du nombre de locations par ville et par genre.
--     Afficher au minimum les colonnes Aventure, Fantasy, Horreur et Shōnen.
--
-- Résultat attendu
--
-- +-------------+----------+---------+----------+---------+
-- | ville       | Aventure | Fantasy | Horreur | Shōnen  |
-- +-------------+----------+---------+----------+---------+
-- | Bordeaux    |        1 |       1 |        0 |       0 |
-- | Lille       |        0 |       0 |        0 |       1 |
-- | Lyon        |        0 |       1 |        0 |       1 |
-- | Marseille   |        0 |       0 |        0 |       1 |
-- | Montpellier |        0 |       0 |        1 |       0 |
-- | Nantes      |        0 |       0 |        0 |       1 |
-- | Nice        |        1 |       0 |        0 |       1 |
-- | Orléans     |        0 |       0 |        1 |       0 |
-- | Paris       |        1 |       0 |        0 |       1 |
-- | Toulouse    |        0 |       0 |        2 |       0 |
-- +-------------+----------+---------+----------+---------+
-- 10 rows in set (0.01 sec)

