-- Task 4
--
-- Instructions
--
--     Afficher les mangas dont le titre contient « Tome 1 ».
--     Affiche uniquement le num_manga et le titre.
--     Trier les résultats par num_manga.
--
-- Résultat attendu
--
-- +-----------+---------------------------------+
-- | num_manga | titre                           |
-- +-----------+---------------------------------+
-- |         1 | One Piece - Tome 1              |
-- |         3 | Naruto - Tome 1                 |
-- |         5 | Dragon Ball - Tome 1            |
-- |         7 | Sailor Moon - Tome 1            |
-- |         9 | L’Attaque des Titans - Tome 1   |
-- |        11 | Fullmetal Alchemist - Tome 1    |
-- |        13 | Ranma 1/2 - Tome 1              |
-- |        15 | Bleach - Tome 1                 |
-- |        17 | Demon Slayer - Tome 1           |
-- |        19 | Jujutsu Kaisen - Tome 1         |
-- |        21 | Death Note - Tome 1             |
-- |        23 | Bakuman - Tome 1                |
-- +-----------+---------------------------------+
-- 12 rows in set (0.01 sec)

SELECT num_manga, titre FROM `mangas` WHERE titre LIKE '%Tome 1%';
