-- Task 16 - Trouver les films d'aventure loues par des clients nes dans
-- les annees 60
--
-- Instructions
--
--     Afficher les titres d'aventure loues par des clients nes dans les
--     annees 60.
--     Utiliser le code genre AV pour les films de genre aventure.
--     Afficher les informations suivantes :
--         - titre du film
--         - nom et prenom du client
--         - date de naissance du client
--     Trier par titre du film.
--
-- Resultat attendu
--
-- +---------------+--------+---------+----------------+
-- | titre         | nom    | prenom  | date_naissance |
-- +---------------+--------+---------+----------------+
-- | Indiana Jones | Girard | Nicolas | 1962-08-09     |
-- | Jurassic Park | Martin | Paul    | 1965-04-12     |
-- | Jurassic Park | Girard | Nicolas | 1962-08-09     |
-- +---------------+--------+---------+----------------+
-- 3 rows in set (0.01 sec)

